# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: home
  url: /
  icon:
- page: 写作
  url: /categories/闲言碎语/
  icon:
- page: 知识
  url: /categories/学习参考/
  icon:
#- page: 生活
#  url: /categories/业余小作/
#  icon:
- page: 归档
  url: /archives/
  icon:
- page: 关于
  url: /posts/b5f422e3/
  icon:

## favicon
favicon: /img/favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: /img/head-img.png

# 各个小工具的设置

## widgets
widgets:
  - notification
  - category
  - archive
  - tagcloud
  - friends
  - social
  - stick

## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: false
    tags: false

## 网站公告设置
notification: |-
    <p style="text-indent: 35px;">
        搭建本站，纯属个人爱好。本站内容为学习过程中所作的笔记与写作留下的痕迹，如遇内容有侵权行为，请给我 <a href="/posts/b5f422e3/" target="_blank">留言</a> 阐述清楚，我将及时处理并删除该内容。
    <hr/>
        主题下载： Snippet <a href="https://github.com/shenliyang/hexo-theme-snippet">原始版</a> | 
                   <a href="https://github.com/dinphy/hexo-theme-snippet">高级版</a>
        <br/>
        主题使用： <a href="https://github.com/shenliyang/hexo-theme-snippet/blob/master/README.md">参考教程</a>
        <br/>
        支持主题： <a href="https://github.com/shenliyang/hexo-theme-snippet/stargazers">Star 一下</a>
    </p>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/dinphy
 - name: 邮箱
   icon: envelope-o
   href: mailto:2027821710@qq.com
 - name: 博客园
   icon: code
   href: //cnblogs.com/dinphy
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   show_count: true
   order: -1

## 友链设置
links:
  - 三步枫: https://blog.adymilk.cn/
  - 珍惜小窝: https://www.zxnest.cn/
  - 慧行说: https://www.liuyude.com/
  - 时节雨: http://web.coder666.cn:18080/
  - 沈立洋博客: http://www.shenliyang.com/
  - 91前端网: http://www.91h5.cc/
  - TZLoop: https://www.whereareyou.site/
  - 猴子星球: https://mr-houzi.com/
  - LzCMS: http://www.lzcms.top/
  - 423down: http://www.423down.com/
  - 装机员: http://www.7xp.com/cj.html
  - th-sjy汉化: http://www.th-sjy.com/
  - 睿派克: https://www.repaik.com/
  - 淡蓝斯宇: http://idoog.me/
  - 申请链接: /posts/b5f422e3/


# 主题自定义个性化配置

## 网站宣传语
branding:

## 设置banner背景图片
banner:
    img: /img/banner.jpg

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  - /img/random/1.jpg
  - /img/random/2.jpg
  - /img/random/3.jpg
  - /img/random/4.jpg
  - /img/random/5.jpg
  - /img/random/6.jpg
  - /img/random/7.jpg
  - /img/random/8.jpg
  - /img/random/9.jpg
  - /img/random/10.jpg  
  - /img/random/11.jpg
  - /img/random/12.jpg
  - /img/random/13.jpg
  - /img/random/14.jpg
  - /img/random/15.jpg
  - /img/random/16.jpg
  - /img/random/17.jpg
  - /img/random/18.jpg
  - /img/random/19.jpg
  - /img/random/20.jpg 
  
## 截取文章首页描述字数
excerptLength: 180

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="/posts/b5f422e3/" target="_blank">Dinphy</a>


## 主题评论

### gitment
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

### Valine评论 参考网站: [valine评论](https://valine.js.org/)
valine:
  enable: true # 如果你想使用valine，请将值设置为 true
  appId: EdyGwWrx3Uxu5hRnY4d4pswD-gzGzoHsz
  appKey: 4pmmj56YRbawceTeHCkLMT7n
  notify: false # 邮件通知
  verify: false # 验证码
  avatar: monsterid # avatar头像: mm/identicon/monsterid/wavatar/retro/hide
  placeholder: Hi,说点什么吧~
  meta: nick,mail,link # 输入框内容，可选值nick,mail,link
  pageSize: 10
  
## 网站访问统计

### 网盟CNZZ统计
cnzz_analytics: 1273798106

### 百度统计
baidu_analytics: 3fabe56e1599321476f3206be87a31b5

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics: 65917606

### “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  enable: true
  site_uv:
  site_pv:

### 百度文章推送
baidu_push: bxXthxpFQo

#网站主题配置
since: 2018
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.1

#网易云音乐ID
musicid: 864820699